version: '3.9'

services:
  aqveir-api:
    container_name: aqveir-api-cont11
    build:
      context: .
      dockerfile: ./scripts/docker/Dockerfile  # Adjust the path to your Dockerfile if necessary
    ports:
      - "8989:80"  # Adjust the port mapping according to your Apache configuration
    networks:
      - aqveir-api-network

networks:
  aqveir-api-network:
    external: true

