version: '3.9'

services:
  aqveir-api:
    stdin_open: true
    tty: true
    privileged: true
    container_name: aqveir-api-cont
    image: aqveir-api-img
    build:
      context: .
      dockerfile: ./scripts/docker/Dockerfile
    ports:
      - "8000:8989"

networks:
  default:
    name: aqveir-api-network
    external: true
